import { NextResponse } from 'next/server';
import { PrismaClient } from '@prisma/client';
import { GoogleGenAI } from '@google/genai';

const prisma = new PrismaClient();
const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
const MODEL_NAME = 'gemini-3.6-flash';

export async function POST(request) {
  try {
    const { projectId } = await request.json();

    if (!projectId) {
      return NextResponse.json({ error: 'Project ID is required' }, { status: 400 });
    }

    // Get project with latest session context
    const project = await prisma.project.findUnique({
      where: { id: projectId },
      include: {
        sessions: {
          orderBy: { startedAt: 'desc' },
          take: 1
        }
      }
    });

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    const latestSession = project.sessions[0];
    const contextDump = latestSession ? latestSession.contextDump : 'No context available. Project has not connected yet.';

    const prompt = `
You are an expert AI Code Forensics Analyzer. Your job is to determine how much of this project was likely generated by an AI (ChatGPT, Copilot, Cursor, etc.) versus hand-written by a human.

Analyze the following project structure and configuration dump:
${contextDump}

Look for:
- Overly generic boilerplate structures.
- Predictable AI file naming conventions.
- Standardized package.json setups without human quirks.
- Lack of complex custom utility folders.

Output MUST be valid JSON only. Do NOT use markdown code blocks.
Format:
{
  "percentage": <integer 0-100>,
  "evidence": [
    {
      "pattern": "Name of the pattern found (e.g. 'Standardized Boilerplate')",
      "explanation": "Brief explanation of why this indicates AI usage or human usage based on the actual data."
    }
  ]
}
`;

    const response = await ai.models.generateContent({
      model: MODEL_NAME,
      contents: prompt,
      config: { temperature: 0.2, responseMimeType: "application/json" }
    });

    const text = (response.text || '').replace(/```json/gi, '').replace(/```/g, '').trim();
    const data = JSON.parse(text);

    return NextResponse.json(data);
  } catch (error) {
    console.error('Analyze AI Usage Error:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
