'use client';

import { useState } from 'react';

export default function AiUsageDetector({ projectId }) {
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState(null);
  const [showEvidence, setShowEvidence] = useState(false);

  const scanCodebase = async () => {
    setLoading(true);
    setError(null);
    setResult(null);
    setShowEvidence(false);

    try {
      const res = await fetch('/api/analyze-ai-usage', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ projectId })
      });
      const data = await res.json();
      
      if (!res.ok) throw new Error(data.error || 'Failed to analyze AI usage');
      
      setResult(data);
    } catch (e) {
      setError(e.message);
    }
    
    setLoading(false);
  };

  return (
    <section className="card" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '1rem' }}>
        <div>
          <h2 style={{ fontSize: '1.25rem', margin: '0 0 0.5rem 0', display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12 2v20M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6"></path></svg>
            AI Code Forensics
          </h2>
          <p style={{ margin: 0, color: 'var(--muted-text)', fontSize: '0.95rem' }}>
            Scan the project architecture, dependencies, and file structures to detect patterns commonly generated by AI (ChatGPT, Copilot, Cursor).
          </p>
        </div>
        
        <button onClick={scanCodebase} disabled={loading}>
          {loading ? <><span className="spinner"></span> Scanning...</> : 'Scan Codebase for AI Usage'}
        </button>
      </div>

      {error && <div className="badge badge-danger" style={{ padding: '0.75rem', borderRadius: '6px', display: 'block', wordBreak: 'break-word', whiteSpace: 'pre-wrap', textTransform: 'none' }}>{error}</div>}

      {result && (
        <div style={{ padding: '1.5rem', backgroundColor: 'var(--background)', borderRadius: '8px', border: '1px solid var(--surface-border)' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '1rem' }}>
            <div>
              <h3 style={{ margin: '0 0 0.5rem 0', fontSize: '1.1rem', color: 'var(--primary)' }}>Detected AI Influence</h3>
              <p style={{ margin: 0, fontSize: '0.9rem', color: 'var(--muted-text)' }}>Based on boilerplate patterns, file structures, and config anomalies.</p>
            </div>
            <div style={{ fontSize: '3rem', fontWeight: 800, color: result.percentage > 50 ? 'var(--danger)' : 'var(--success)' }}>
              {result.percentage}%
            </div>
          </div>
          
          <div style={{ marginTop: '1.5rem' }}>
            <button 
              onClick={() => setShowEvidence(!showEvidence)}
              style={{ background: 'transparent', border: '1px solid var(--primary)', padding: '0.5rem 1rem', fontSize: '0.85rem' }}
            >
              {showEvidence ? 'Hide Evidence' : 'View Detection Evidence'}
            </button>
            
            {showEvidence && (
              <div style={{ marginTop: '1rem', display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
                {result.evidence.map((ev, i) => (
                  <div key={i} style={{ padding: '1rem', backgroundColor: 'var(--surface)', borderRadius: '6px', borderLeft: '4px solid var(--primary)' }}>
                    <p style={{ margin: '0 0 0.5rem 0', fontWeight: 600, color: 'var(--foreground)' }}>{ev.pattern}</p>
                    <p style={{ margin: 0, fontSize: '0.9rem', color: 'var(--muted-text)' }}>{ev.explanation}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      )}
    </section>
  );
}
